source "http://gems.rubyforge.org"
source 'http://rubygems.org'


gem 'rack'
gem 'sinatra'
gem 'tweetstream'
gem 'racksh'
gem 'yajl-ruby'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'sinatra-activerecord'
gem 'activerecord'
gem 'sqlite3'
gem 'shotgun'
gem 'redis'
gem 'geokit'
gem 'pg'
gem 'fb_graph'
gem 'nestful'
gem 'posterous'
gem 'rest-client'